### ISSUE TITLE
Marginal plot scaling

### ISSUE THREAD

**Issue by nneveu** [ChristopherMayes/openPMD-beamphysics#1]
When zooming in on a phase space plot, the projections in y and x do not scale with the zoom.
They are static and always remain the same scale. See example below after zooming in, histograms do not follow:

![lcls2_gun_opt_phase_space2](https://user-images.githubusercontent.com/22915937/73893305-21bdbe00-482e-11ea-8586-65631b84a9ee.png)

**Comment by ChristopherMayes** [comment]
@nneveu This should be fixed now

**Comment by ChristopherMayes** [comment]
Also see #44
