### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by st-walker** [ChristopherMayes/openPMD-beamphysics#15]
Hello,

This is a nice package.  It would be great if this package was also on PyPI so one could include it in a setup.py easily.  I understand that there are alternative methods like linking directly within the setup.py to some asset associated with this github repository, but it would nevertheless be easier to just have it on PyPI like the main openPMD repository and its  friends.

**Comment by ChristopherMayes** [comment]
@st-walker Done, with the help of @hhslepicka. All the work is done by the GitHub action, on every release.
