### ISSUE TITLE
add example data

### ISSUE THREAD

**Issue by bwheelz36** [ChristopherMayes/openPMD-beamphysics#36]
Could I also suggest for the docs, pointing to an example dataset that people could quickly download and play with - maybe [this one](https://github.com/openPMD/openPMD-example-datasets)?

**Comment by ChristopherMayes** [comment]
All of the data associated with the docs are within this repository: https://github.com/ChristopherMayes/openPMD-beamphysics/tree/master/docs/examples/data. Do you still suggest something separate?

**Comment by bwheelz36** [comment]
no, that seems good - it's more that it wasn't clear to me looking through the docs where this data is? Perhaps I missed this statement though?

**Comment by ChristopherMayes** [comment]
The docs notebooks work when cloning this entire repository. I could think of a different way.

**Comment by bwheelz36** [comment]
in my case, I pip installed the package and then wanted to play with the data. Now I look more closely I should have been able to figure out where it was! 
Anyway I would just suggest a note at the top of the examples "The data used in these examples can be downloaded [here]()" but totally up to you :-)
